# Numpy Challenge

Computing the row-wise counts of all possible values in arrays

# Given Input

In [1]:
import numpy as np
np.random.seed(100)
arr= np.random.randint(1,11,size=(6,10))
arr


array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

# Solution Output

In [2]:
for i in range(len(arr)):
    counter = np.bincount(arr[i])
    print(counter)
    

[0 1 0 2 1 1 1 0 2 2]
[0 2 1 3 0 1 0 1 0 1 1]
[0 0 3 0 2 3 1 0 1]
[0 1 0 2 1 0 1 0 2 1 2]
[0 2 2 2 0 0 1 1 1 1]
[0 1 1 1 1 1 2 0 0 2 1]


# Pandas Challenge Solution

In [3]:
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv',usecols=[0,1,2,3,5])
df[['Manufacturer', 'Model','Type']] = df[['Manufacturer','Model','Type']].fillna(value='missing')
df["Index"]=df["Manufacturer"].astype(str)+'_'+df["Model"]+'_'+df["Type"]
df.set_index('Index', inplace=True)
df

Manufacturer    Model     Type  Min.Price  Max.Price
Index                                                                         
Acura_Integra_Small              Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize         missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                   Audi       90  Compact       25.9       32.3
Audi_100_Midsize                  Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                   BMW     535i  Midsize        NaN        NaN
...                                ...      ...      ...        ...        ...
Volkswagen_Eurovan_Van      Volkswagen  Eurovan      Van       16.6       22.7
Volkswagen_Passat_Compact   Volkswagen   Passat  Compact       17.6       22.4
Volkswagen_Corrado_Sporty   Volkswagen  Corrado   Sporty       22.9       23.7
Volvo_240_Compact                Volvo      240  Compact       21.8       23.5
missing_850_Midsize            missing      850  Midsize       24.8       28.5

[93 rows x 5 columns]